version: '3.9'

services:
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef:latest
    ports:
      - 8080:8000
    restart: unless-stopped
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
     test: curl -f http://localhost:8000/ || exit 1